### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by DomSheehy** [veryfi/veryfi-ruby#18]
It looks like the release action for 1.0.2 never pushed the update to rubygems. Wondering if someone can take a look and bump the version for the faraday dependency

Thanks

**Comment by saboter** [comment]
It would be nice to have it properly updated in ruby gems.

It will be one whole year soon since similar question was posted by me:

https://github.com/veryfi/veryfi-ruby/pull/15#issuecomment-1373466844

**Comment by DomSheehy** [comment]
It looks like it's staged? https://github.com/veryfi/veryfi-ruby/actions/runs/3887174691 @Kaevan89, anyway I can help?

**Comment by manycoding** [comment]
Thanks for raising this one. Looks like the version was not updated in `lib/veryfi/version.rb` which failed release.
I just released 1.0.2
