### ISSUE TITLE
Get BadRequest response with Readme example

### ISSUE THREAD

**Issue by ghost** [veryfi/veryfi-ruby#2]
Given:
* Have valid credentials on Veryfi.com and set them on the docker.env file
* Create VeryfiClient instance with the next code
```
VeryfiClient = Veryfi::Client.new(
  client_id: ENV.fetch('VERYFI_CLIENT_ID', nil),
  client_secret: ENV.fetch('VERYFI_CLIENT_SECRET', nil),
  username: ENV.fetch('VERYFI_USERNAME', nil),
  api_key: ENV.fetch('VERYFI_API_KEY', nil),
)
```

* set request parameters as described on README
```
params = {
  file_path: 'spec/fixtures/purchase_vendor_bills/vendor_bill.pdf',
  auto_delete: true,
  boost_mode: false,
  async: false,
  external_id: '123456789',
  max_pages_to_process: 10,
  tags: ['tag1'],
  categories: [
    'Advertising & Marketing',
    'Automotive'
  ]
}
```
Then make a request with the below code
` VeryfiClient.document.process(params)`

and got an error

```
Veryfi::Error::BadRequest: Bad Request
from /project_gems/ruby/2.7.0/gems/veryfi-0.1.3/lib/veryfi/request.rb:63:in `make_request'
```
The same result with only :file_path parameter
```
params = {
  file_path: 'spec/fixtures/purchase_vendor_bills/vendor_bill.pdf',
}
```
UPDATE:: Made some investigation. 

API responses 400 when "file_name" POST-parameter hasn't extension.
For example, 
``` 
{
  "file_name": "invoice",
  "file_data": "application/pdf;base64,JVBERi0xLjQKJcfsj6IKJSVJbnZvY......."
}
```
returns 400

But
``` 
{
  "file_name": "invoice.pdf",
  "file_data": "application/pdf;base64,JVBERi0xLjQKJcfsj6IKJSVJbnZvY........"
}
```
returns 201.

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/87445621/136270338-b9754f13-e6fb-4b51-bd12-c74e22f0f044.mp4

**Comment by manycoding** [comment]
I confirm, looks like the filename is not passed along with base64 which is important.
Also the SDK doesn't pass the error message back which is
```
{
    "status": "fail",
    "error": "No files to process"
}
```
@astepanenko-modularity you are welcome to submit a fix
