### ISSUE TITLE
Newly released 1.0.2 gem is not loading properly in rails project

### ISSUE THREAD

**Issue by saboter** [veryfi/veryfi-ruby#20]
Hi,
it seems that the latest 1.0.2 gem is not working properly:

- removed `gem "veryfi", git: "https://github.com/veryfi/veryfi-ruby.git"` from my Gemfile
- added `gem "veryfi", "~> 1.0.2"`
- `bundle update veryfi`
- new gem was installed
- spec started to fail because the veryfi gem was not properly loaded
- require 'veryfi' in the console fails as well

Same behavior/issue is present in freshly created rails app.

Thanks.

Martin

**Comment by DomSheehy** [comment]
@manycoding It looks like the version on rubygems is a blank folder, could you double check the publishing process? Thanks, and sorry for the trouble!

**Comment by manycoding** [comment]
Just released 1.0.4, should be it
